<?php

/**
 * Test class for NKUser.
 * Generated by PHPUnit on 2011-12-05 at 16:50:09.
 */
class NKUserTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var NKUser
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $data = json_decode('{
    "entry":{
     "profileUrl":"http://nk.pl/profile/1",
     "gender":"male",
     "hasApp":true,
     "id":"person.abc",
     "age":31,
     "nkFriendsCount":57,
     "thumbnailUrl":"http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg",
     "name":{
       "formatted":"Anna Kowalska (Nowak)",
       "additionalName":"Kowalska (Nowak)",
       "familyName":"Kowalska",
       "givenName":"Anna"
     },
     "urls":[{"value":"http://nk.pl/profile/1","type":"profile"}],
     "photos":[
       {
         "value":"http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg",
         "type":"thumbnail"
       }],
     "displayName":"Mr Sponge",
     "currentLocation":{
       "region":"WrocLove"
     }
    }
    }', true);

    $this->object = new NKUser;
    $this->object->assignData($data['entry']);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   *
   */
  public function testId()
  {
    $this->assertSame('person.abc', $this->object->id());
  }

  /**
   *
   */
  public function testName()
  {
    $this->assertSame('Mr Sponge', $this->object->name());
  }

  /**
   *
   */
  public function testPhotos()
  {
    $photos = $this->object->photos();

    $this->assertTrue(is_array($photos));
    $this->assertEquals(1, count($photos));


    $photo = current($photos);

    $this->assertTrue(is_array($photo));
    $this->assertArrayHasKey('value', $photo);
    $this->assertEquals('http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg', $photo['value']);
  }

  /**
   *
   */
  public function testThumbnailUrl()
  {
    $this->assertEquals('http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg', $this->object->thumbnailUrl());
  }

  /**
   *
   */
  public function testEmail()
  {
    $this->assertNull($this->object->email());
  }

  /**
   *
   */
  public function testAge()
  {
    $this->assertEquals(31, $this->object->age());
  }

  /**
   *
   */
  public function testGender()
  {
    $this->assertEquals('male', $this->object->gender());
  }

  /**
   *
   */
  public function testLocation()
  {
    $this->assertEquals('WrocLove', $this->object->location());
  }

  /**
   *
   */
  public function testFriendsCount()
  {
    $this->assertEquals(57, $this->object->friendsCount());
  }

  /**
   *
   */
  public function testPhoneNumber()
  {
    $this->assertNull($this->object->phoneNumber());
  }

  /**
   *
   */
  public function testBirthday()
  {
    $this->assertNull($this->object->birthday());
  }
}
?>
