<?php

/**
 * Test class for NKUser.
 * Generated by PHPUnit on 2011-12-05 at 16:50:09.
 */
class NKUserExtendedTest extends PHPUnit_Framework_TestCase
{
  /**
   * @var NKUser
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $data = json_decode('{
    "entry":{
     "profileUrl":"http://nk.pl/profile/1",
     "gender":"male",
     "hasApp":true,
     "id":"person.abc",
     "age":31,
     "nkFriendsCount":57,
     "thumbnailUrl":"http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg",
     "name":{
       "formatted":"Anna Kowalska (Nowak)",
       "additionalName":"Kowalska (Nowak)",
       "familyName":"Kowalska",
       "givenName":"Anna"
     },
     "urls":[{"value":"http://nk.pl/profile/1","type":"profile"}],
     "photos":[
       {
         "value":"http://photos.nasza-klasa.pl/125/10/thumb/6646b702e7.jpeg",
         "type":"thumbnail"
       }],
     "displayName":"Mr Sponge",
     "currentLocation":{
       "region":"WrocLove"
     },
     "emails":[
         {"value":"some@email.com","type":"email"}
     ],
     "phoneNumbers":[
         {"value":"my E51","type":"phone_number"}
     ],
     "birthday":"1991-11-23T23:00:00.000Z"
    }
    }', true);

    $this->object = new NKUser;
    $this->object->assignData($data['entry']);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   *
   */
  public function testId()
  {
    $this->assertSame('person.abc', $this->object->id());
  }

  /**
   *
   */
  public function testEmail()
  {
    $this->assertSame('some@email.com', $this->object->email());
  }

  /**
   *
   */
  public function testPhoneNumber()
  {
    $this->assertSame('my E51', $this->object->phoneNumber());
  }

  /**
   *
   */
  public function testBirthday()
  {
    $this->assertSame('1991-11-24', $this->object->birthday());
  }
}
?>
